// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.DATA.Data;

#nullable disable

namespace Quiz.DATA.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quiz.DATA.Entity.Questao", b =>
                {
                    b.Property<int>("QuestaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaE")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("QuestaoId");

                    b.ToTable("Questoes");
                });

            modelBuilder.Entity("Quiz.DATA.Entity.Resposta", b =>
                {
                    b.Property<int>("RespostaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternativaCorreta")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<int>("QuestaoId")
                        .HasColumnType("int");

                    b.HasKey("RespostaId");

                    b.HasIndex("QuestaoId")
                        .IsUnique();

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("Quiz.DATA.Entity.Resposta", b =>
                {
                    b.HasOne("Quiz.DATA.Entity.Questao", "Questao")
                        .WithOne("Resposta")
                        .HasForeignKey("Quiz.DATA.Entity.Resposta", "QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("Quiz.DATA.Entity.Questao", b =>
                {
                    b.Navigation("Resposta");
                });
#pragma warning restore 612, 618
        }
    }
}
