// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.API.Data;

#nullable disable

namespace Quiz.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241025234036_answers")]
    partial class answers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Quiz.API.Data.Entity.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("AnswerValue")
                        .HasColumnType("varchar(2)");

                    b.Property<int>("AskId")
                        .HasColumnType("int");

                    b.Property<string>("ValueA")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ValueB")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ValueC")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ValueD")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("ValueE")
                        .HasColumnType("varchar(300)");

                    b.HasKey("AnswerId");

                    b.HasIndex("AskId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Quiz.API.Data.Entity.Ask", b =>
                {
                    b.Property<int>("AskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AskId"));

                    b.Property<string>("Title")
                        .HasColumnType("varchar(100)");

                    b.HasKey("AskId");

                    b.ToTable("Asks");
                });

            modelBuilder.Entity("Quiz.API.Data.Entity.Answer", b =>
                {
                    b.HasOne("Quiz.API.Data.Entity.Ask", "Ask")
                        .WithMany("Answers")
                        .HasForeignKey("AskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ask");
                });

            modelBuilder.Entity("Quiz.API.Data.Entity.Ask", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
