// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.API.Data;

#nullable disable

namespace Quiz.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241005001138_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Quiz.API.Data.Entity.Ask", b =>
                {
                    b.Property<int>("AskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AskId"));

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("AskId");

                    b.ToTable("Asks");
                });
#pragma warning restore 612, 618
        }
    }
}
