// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quiz.DATA.Data;

#nullable disable

namespace Quiz.DATA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220929223805_update-questoes")]
    partial class updatequestoes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Quiz.DATA.Entity.Questao", b =>
                {
                    b.Property<int>("QuestaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AlternativaA")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaB")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaC")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaD")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AlternativaE")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("QuestaoId");

                    b.ToTable("Questao");
                });
#pragma warning restore 612, 618
        }
    }
}
